; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_raw = true

[common]
platform_esp32_espressif = espressif32
platform_esp32_pioarduino = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
lib_deps =
build_flags =
partitions = default_ffat.csv

; MIXIN: Completely optional external 128x64 SSD1306 OLED screen for status
[display128x64]
lib_deps =
	adafruit/Adafruit SSD1306@^2.5.16
	adafruit/Adafruit GFX Library@^1.12.4
build_flags = -DENABLE_DISPLAY_128x64

; MIXIN: Completely optional PSRAM as destination for watch dump, falls back to flash
[psram]
lib_deps = tobozo/ESP32-PSRamFS@^1.0.7 ;See readme for potentially required fix
build_flags = -DENABLE_PSRAM

[env:lolin_s2_mini]
platform = espressif32
framework = arduino
board = lolin_s2_mini
board_build.mcu = esp32s2
board_build.partitions = ${common.partitions}

[env:lolin_s2_mini-display128x64]
platform = espressif32
framework = arduino
board = lolin_s2_mini
board_build.mcu = esp32s2
board_build.partitions = ${common.partitions}
lib_deps = ${display128x64.lib_deps}
build_flags = ${display128x64.build_flags}

[env:lolin_s2_mini-display128x64-psram]
platform = espressif32
framework = arduino
board = lolin_s2_mini
board_build.mcu = esp32s2
board_build.partitions = ${common.partitions}
lib_deps =
	${display128x64.lib_deps}
	${psram.lib_deps}
build_flags =
	${display128x64.build_flags}
	${psram.build_flags}

[env:esp32_s3_supermini]
platform = espressif32
framework = arduino
board = esp32-s3-fh4r2
; board_build.mcu = esp32s3
board_build.partitions = ${common.partitions}

[env:esp32_c3_supermini-builtin-oled]
platform = espressif32
framework = arduino
board = nologo_esp32c3_super_mini
; board_build.mcu = esp32c3
board_build.partitions = ${common.partitions}
lib_deps = olikraus/U8g2@^2.36.17
build_flags = -DENABLE_DISPLAY_72x40 -DPIN_LED=8 -DPIN_BUTTON=9
